### ISSUE TITLE
Ban Reason does not get URL-Encoded

### ISSUE THREAD

**Issue by garantiertnicht** [Katrix/AckCord#16]
Using the latest 0.13.0, the route for bans does not get properly encoded.

# Steps to reproduce
* Send a CreateGuildBan request with a space in the reason (`someMember.ban(Some(1), Some("Best Reason Evar"))`)

# Expected Results
The REST-Call succeeds (provided permissions etc.)

# Actual Results
```
akka.http.scaladsl.model.IllegalUriException: Illegal URI reference: Invalid input ' ', expected raw-query-char, '#' or 'EOI' (line 1, column 114): https://discordapp.com/api/v6/guilds/<guildid>/bans/<userid>?delete-message-days=1&reason=Best Reason Evar
                                                                                                                 ^
	at akka.http.scaladsl.model.IllegalUriException$.apply(ErrorInfo.scala:74)
	at akka.http.scaladsl.model.Uri$.fail(Uri.scala:823)
	at akka.http.impl.model.parser.UriParser.fail(UriParser.scala:81)
	at akka.http.impl.model.parser.UriParser.parseUriReference(UriParser.scala:46)
	at akka.http.scaladsl.model.Uri$.apply(Uri.scala:217)
	at akka.http.scaladsl.model.Uri$.apply(Uri.scala:189)
	at ackcord.requests.Routes$QueryRoute.$anonfun$$plus$qmark$2(Routes.scala:117)
	at scala.Function$.$anonfun$uncurried$1(Function.scala:50)
	at scala.Function2.$anonfun$tupled$1(Function2.scala:53)
	at ackcord.requests.Routes$QueryRouteFunction.$anonfun$toRequest$2(Routes.scala:170)
	at shapeless.ops.FnFromProductInstances$$anon$5.$anonfun$apply$5(fnfromproduct.scala:89)
	at ackcord.requests.CreateGuildBan.route(guildRequests.scala:504)
	at ackcord.requests.RequestStreams$.$anonfun$ratelimitFlow$1(RequestStreams.scala:158)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1375)
	…```

**Comment by Katrix** [comment]
Fixed in the latest release
