### ISSUE TITLE
Weird exception logged for no reason

### ISSUE THREAD

**Issue by AlexITC** [Katrix/AckCord#24]
I'm getting an exception logged, which seems related to another one due to missing permissions, this occurred while trying to send a message:
```
ackcord.requests.HttpException: 403, Forbidden {"message": "Missing Access", "code": 50001}
	at ackcord.requests.RequestStreams$.$anonfun$requestParser$3(RequestStreams.scala:303)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Weird exception:
```
java.util.NoSuchElementException: head of empty stream
	at akka.stream.scaladsl.Sink$.$anonfun$head$3(Sink.scala:197)
	at scala.Option.getOrElse(Option.scala:201)
	at akka.stream.scaladsl.Sink$.$anonfun$head$2(Sink.scala:197)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:164)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at akka.stream.impl.HeadOptionStage$$anon$3.onUpstreamFinish(Sinks.scala:235)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:758)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.util.NoSuchElementException: head of empty stream
	at akka.stream.scaladsl.Sink$.$anonfun$head$3(Sink.scala:197)
	at scala.Option.getOrElse(Option.scala:201)
	at akka.stream.scaladsl.Sink$.$anonfun$head$2(Sink.scala:197)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:164)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
```

**Comment by AlexITC** [comment]
Another one when sending the message succeeded:
```
a.a.t.ActorSystem - Unhandled exception in stream
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at ackcord.data.raw.RawMessage.toMessage(rawData.scala:408)
	at ackcord.cachehandlers.CacheHandlers$$anon$15.$anonfun$handle$78(CacheHandlers.scala:380)
	at ackcord.cachehandlers.CacheTypeRegistry.$anonfun$handleWithData$1(CacheTypeRegistry.scala:45)
	at ackcord.cachehandlers.CacheTypeRegistry.$anonfun$handleWithData$1$adapted(CacheTypeRegistry.scala:45)
	at scala.Option.foreach(Option.scala:437)
	at ackcord.cachehandlers.CacheTypeRegistry.handleWithData(CacheTypeRegistry.scala:45)
	at ackcord.cachehandlers.CacheTypeRegistry.updateData(CacheTypeRegistry.scala:48)
	at ackcord.cachehandlers.CacheHandlers$$anon$15.handle(CacheHandlers.scala:380)
	at ackcord.cachehandlers.CacheHandlers$$anon$15.handle(CacheHandlers.scala:374)
	at ackcord.APIMessageCacheUpdate.process(cacheUpdates.scala:57)
	at ackcord.CacheStreams$.$anonfun$cacheUpdater$2(CacheStreams.scala:119)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$49.onPush(Ops.scala:2192)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:495)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at ackcord.data.raw.RawMessage.toMessage(rawData.scala:408)
	at ackcord.cachehandlers.CacheHandlers$$anon$15.$anonfun$handle$78(CacheHandlers.scala:380)
	at ackcord.cachehandlers.CacheTypeRegistry.$anonfun$handleWithData$1(CacheTypeRegistry.scala:45)
	at ackcord.cachehandlers.CacheTypeRegistry.$anonfun$handleWithData$1$adapted(CacheTypeRegistry.scala:45)
	at scala.Option.foreach(Option.scala:437)
	at ackcord.cachehandlers.CacheTypeRegistry.handleWithData(CacheTypeRegistry.scala:45)
	at ackcord.cachehandlers.CacheTypeRegistry.updateData(CacheTypeRegistry.scala:48)
	at ackcord.cachehandlers.CacheHandlers$$anon$15.handle(CacheHandlers.scala:380)
```

**Comment by Katrix** [comment]
Thanks for this. I'm assuming you're using `RequestHelper#run`, in which case this should now be fixed. If you're not using that, then it might be that the behavior is as intended (`success` in `Requests` are very optimistic) As for the other one, unrelated fixed issue.

**Comment by AlexITC** [comment]
Yes, I'm using `RequestHelper#run`, thanks for the quick fixes.
