### ISSUE TITLE
Error in stage Upstream producer failed with exception, removing from MergeHub now

### ISSUE THREAD

**Issue by AlexITC** [Katrix/AckCord#25]
I have a bot running that has been printing this error several times, any suggestions to prevent it?

```
2020-07-12 09:59:25,391 [ERROR] from akka.actor.RepointableActorRef in AckCord-akka.actor.default-dispatcher-5272 - Error in stage [akka.stream.scaladsl.MergeHub$$anon$2@2b900b4e]: Upstream producer failed with exception, removing from MergeHub now
akka.http.scaladsl.model.ws.PeerClosedConnectionException: Peer closed connection with code 4000 'Unknown error.'
	at akka.http.impl.engine.ws.WebSocket$PrepareForUserHandler$$anon$1.onPush(WebSocket.scala:115)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:495)
	... 20 common frames omitted
Wrapped by: akka.stream.scaladsl.MergeHub$ProducerFailed: Upstream producer failed with exception, removing from MergeHub now
	at akka.stream.scaladsl.MergeHub$$anon$2$$anon$3.onUpstreamFailure(Hub.scala:276)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:55)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:51)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:94)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
akka.stream.scaladsl.MergeHub$ProducerFailed: Upstream producer failed with exception, removing from MergeHub now
	at akka.stream.scaladsl.MergeHub$$anon$2$$anon$3.onUpstreamFailure(Hub.scala:276)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:55)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:51)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:94)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: akka.http.scaladsl.model.ws.PeerClosedConnectionException: Peer closed connection with code 4000 'Unknown error.'
	at akka.http.impl.engine.ws.WebSocket$PrepareForUserHandler$$anon$1.onPush(WebSocket.scala:115)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:495)
	... 20 common frames omitted
2020-07-12 10:04:25,392 [INFO] from ackcord.DiscordShard$ in AckCord-akka.actor.default-dispatcher-5627 - Gateway handler shut down. Restarting in 5 minutes
```

**Comment by Katrix** [comment]
Hm, hard to say. I've been doing a lot of changes to the gateway code, so it could be fixed in master...?

For this case, could you enable debug logs and see if anything interesting jumps out?

As for release, probably once the refactored gateway code is stable.

**Comment by AlexITC** [comment]
I'll enable debug logs and let you know if it occurs again, I'm using version `0.16.1`.

Thanks.

**Comment by Katrix** [comment]
This should be fixed in master now

**Comment by AlexITC** [comment]
Thanks, I'll update and let you know if it occurs again.

**Comment by AlexITC** [comment]
Actually, I can't compile `master` due to an error:

```
[error] AckCord/commandsOldCore/src/main/scala/ackcord/oldcommands/CmdStreams.scala:46:38: wrong number of arguments for pattern ackcord.APIMessage.MessageCreate(guild: Option[ackcord.data.Guild], message: ackcord.data.Message, cache: ackcord.CacheState)
[error]         case APIMessage.MessageCreate(msg, c) =>
[error]                                      ^
```
