### ISSUE TITLE
ERROR: actor name [GatewayHandler] is not unique!

### ISSUE THREAD

**Issue by AlexITC** [Katrix/AckCord#26]
Another error I got, which looks like a race condition occurring somewhere on the actor creation.

Also, do you have any plans to release the latest fixes anytime soon? Thanks.

```
2020-07-12 10:09:25,415 [ERROR] from akka.actor.SupervisorStrategy in AckCord-akka.actor.default-dispatcher-5634 - actor name [GatewayHandler] is not unique!
akka.actor.InvalidActorNameException: actor name [GatewayHandler] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:134)
	at akka.actor.dungeon.Children.reserveChild(Children.scala:139)
	at akka.actor.dungeon.Children.reserveChild$(Children.scala:137)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:408)
	at akka.actor.dungeon.Children.makeChild(Children.scala:291)
	at akka.actor.dungeon.Children.actorOf(Children.scala:47)
	at akka.actor.dungeon.Children.actorOf$(Children.scala:46)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:408)
	at akka.actor.typed.internal.adapter.ActorRefFactoryAdapter$.spawn(ActorRefFactoryAdapter.scala:41)
	at akka.actor.typed.internal.adapter.ActorContextAdapter.spawn(ActorContextAdapter.scala:66)
	at ackcord.DiscordShard$.$anonfun$shard$1(DiscordShard.scala:124)
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:152)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:119)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:105)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
akka.actor.InvalidActorNameException: actor name [GatewayHandler] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:134)
	at akka.actor.dungeon.Children.reserveChild(Children.scala:139)
	at akka.actor.dungeon.Children.reserveChild$(Children.scala:137)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:408)
	at akka.actor.dungeon.Children.makeChild(Children.scala:291)
	at akka.actor.dungeon.Children.actorOf(Children.scala:47)
	at akka.actor.dungeon.Children.actorOf$(Children.scala:46)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:408)
	at akka.actor.typed.internal.adapter.ActorRefFactoryAdapter$.spawn(ActorRefFactoryAdapter.scala:41)
	at akka.actor.typed.internal.adapter.ActorContextAdapter.spawn(ActorContextAdapter.scala:66)
	at ackcord.DiscordShard$.$anonfun$shard$1(DiscordShard.scala:124)
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:152)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:119)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:105)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2020-07-12 10:09:25,425 [INFO] from akka.actor.LocalActorRef in AckCord-akka.actor.default-dispatcher-5629 - Message [scala.util.Success] wrapped in [akka.actor.typed.internal.AdaptMessage] to Actor[akka://AckCord/system/DiscordClient/Shard0/GatewayHandler#51704895] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://AckCord/system/DiscordClient/Shard0/GatewayHandler#51704895] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by Katrix** [comment]
Well that was a stupid bug

**Comment by AlexITC** [comment]
Thanks!
