### ISSUE TITLE
Verifier IndexOutOfBoundsException issues

### ISSUE THREAD

**Issue by Yomanz** [Katrix/AckCord#74]
This issue seems to be happening frequently:

In this example, `content` was empty as I was sending embeds which is a valid body.
```
java.lang.IndexOutOfBoundsException: null

    at java.base/java.lang.String.codePointCount(String.java:1607)

    at ackcord.util.Verifier$.stringLength(Verifier.scala:102)

    at ackcord.util.Verifier$.requireLength(Verifier.scala:18)

    at ackcord.requests.CreateMessageData.<init>(channelRequests.scala:319)

    at ackcord.syntax.package$TextChannelSyntax$.sendMessage$extension(syntax.scala:120)
```

This comes from within ackcord when parsing from discord so there's not much I can do to patch it on my end.
```
java.lang.String
in codePointCount at line 1610
ackcord.util.Verifier$
in stringLength at line 102
ackcord.util.Verifier$
in requireLength at line 18
ackcord.data.EmbedField
in <init> at line 784
ackcord.data.DiscordProtocol$$anon$26
in apply at line 192
io.circe.SeqDecoder
in apply at line 17
io.circe.Decoder$$anon$39
in tryDecode at line 930
ackcord.data.DiscordProtocol$$anon$33
in apply at line 213
io.circe.SeqDecoder
in apply at line 17
io.circe.Decoder$$anon$39
in tryDecode at line 930
io.circe.ACursor
in as at line 211
ackcord.util.JsonOption$
in $anonfun$decodeRestOption$1 at line 33
io.circe.Decoder$$anon$19
in tryDecode at line 526
io.circe.ACursor
in as at line 211
io.circe.ACursor
in get at line 218
ackcord.gateway.GatewayProtocol$
in $anonfun$rawPartialMessageDecoder$15 at line 235
```

**Comment by Katrix** [comment]
Fixed in latest release
